"""empty message

Revision ID: 1d0bb67cb3ed
Revises: 711079720b6b
Create Date: 2025-09-02 15:18:26.707357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0bb67cb3ed'
down_revision = '711079720b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
